//
// Created by Nick on 08.11.2025.
//

#ifndef LIION_CONTROL_COLOR_SPACE_H
#define LIION_CONTROL_COLOR_SPACE_H

#define PAGE_COLOR TFT_WHITE
#define MAIN_FONT_COLOR TFT_BLACK
#define MAIN_BUTTON_LINE_COLOR TFT_BLACK

#endif //LIION_CONTROL_COLOR_SPACE_H